version: '3'

services:

  latest:
    image: tmvdl/go:latest
    build: './src/latest'

  alpine:
    image: tmvdl/go:alpine
    build: './src/alpine'

  revel:
    image: tmvdl/go:revel
    build: './src/revel'
