version: '3'

services:

  latest:
    image: 'tmvdl/go:latest'
    build: './src/latest'

  alpine:
    image: 'tmvdl/go:alpine'
    build: './src/alpine'

  revel:
    image: 'tmvdl/go:revel'
    build: './src/revel'

  buffalo:
    image: 'tmvdl/go:buffalo'
    build: './src/buffalo'

  gin:
    image: 'tmvdl/go:gin'
    build: './src/gin'

  # beego:
  #   image: 'tmvdl/go:beego'
  #   build: './src/beego'

  echo:
    image: 'tmvdl/go:echo'
    build: './src/echo'

  fiber:
    image: 'tmvdl/go:fiber'
    build: './src/fiber'
